# -*- coding: utf-8 -*-
"""BodyMassIndex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzDkNvf7w-MHB7sxZFWjkHJxEXCRm_d4

#**Exercise 3: Body Mass Index (BMI)**

---
"""

# BodyMassIndex.py
weight = float(input("Enter your weight in (kg): "))
height = float(input("Enter your height in (m): "))

bmi = weight / (height ** 2)
print(f"Your BMI is: {bmi:.2f}")

if bmi < 18.5:
    status = "Underweight"
elif 18.5 <= bmi < 25:
    status = "Normal"
elif 25 <= bmi < 30:
    status = "Overweight"
else:
    status = "Obese"

print(f"You are in the “{status}” range.")

"""#**Exercise 4: Greatest of Three Numbers**

---


"""

#greatest of 3 numbers

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

greatest = max(num1, num2, num3)
print(f"The greatest number is {greatest}")

"""#**Exercise 5: Factorial of a Number**

---


"""

#factorial of number

num = int(input("Enter a number: "))
factorial = 1

for i in range(1, num + 1):
    factorial *= i

print(f"The factorial of {num} is {factorial}")

"""#**Exercise 6: Reverse a Number**

---


"""

#reversing a number

num = int(input("Enter a number: "))
reversed_num = 0

while num > 0:
    remainder = num % 10
    reversed_num = reversed_num * 10 + remainder
    num = num // 10

print(f"The reversed number is {reversed_num}")

"""#**Exercise 7: Multiples of a Number**

---


"""

#multiples of a number using loop

num = int(input("Enter a number: "))
limit = int(input("Enter the limit: "))

for i in range(1, limit + 1):
    if i % num == 0:
        print(i)

"""#**Exercise 8: Break the Loop on 'done'**

---


"""

while True:
    text = input(":")
    if text == 'done':
        print("Done")
        break
    print(text)

"""#**Exercise 9: FizzBuzz**

---


"""

for i in range(1, 11):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

"""#**Exercise 10: Print Pattern**

---


"""

#pattern

for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        print(j, end=" ")
    print()